export { default as TruckModal } from './TruckModal'
export { default as WimModal } from './WimModal'
export { default as TruckMoveModal } from './TruckMoveModal'
export { default as ModalPic } from './ModalPic'
export { default as FormMove } from './FormMove'