export { default as Cardboard } from "./Cardboard";
export { default as Weight } from "./Weight";
export { default as Hashtag } from "./Hashtag";
export { default as Speed } from "./Speed";
export { default as TruckWheel } from "./TruckWheel";
export { default as BigTruck } from "./BigTruck";
export { default as Bin } from "./Bin";
export { default as CCTVIcon } from "./CCTVIcon";
export { default as Edit } from "./Edit";
export { default as Failed } from "./Failed";
export { default as PhTruck } from "./PhTruck";
export { default as SmallTruck } from "./SmallTruck";
export { default as Success } from "./Success";
export { default as TruckIcon } from "./TruckIcon";
export { default as Weightbox } from "./Weightbox";
export { default as PaperIcon } from "./PaperIcon";
export { default as WeightIcon } from "./WeightIcon";
export { default as CCTVInactive } from './CCTVInactive'
export { default as MovingVehicle } from './MovingVehicle'
export { default as StationVehicle } from './StationVehicle'
export { default as OverWeightVehicle } from './OverWeightVehicle'